<keyword> ::= <specific strings token>
<symbol> ::= '{', '}', '(', ')', '[', ']', '.', ',', ';', '+', '-', '*', '/', '&', '|', '<', '>', '=', '~'
<strConst> ::= '"' [A-Z, a-z, 0-9, _]* '"'
<ident> ::= [A-Z, a-z, _] [A-Z, a-z, 0-9, _]*
